# Generated by Django 2.0.6 on 2018-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_one_auth', '0002_auto_20180702_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
